### ISSUE TITLE
raze compatibility

### ISSUE THREAD

**Issue by Unikat2000** [fgsfds/Shadow-Warrior-Voxel-Pack#1]
Hi,

it seems that the current maphacks are NOT compatible with raze (tested with 1.1.2).  When raze tries to load them it crashes immediately.

**Comment by Dzierzan** [comment]
Hi, I have this similar issue here:

https://github.com/coelckers/Raze/issues/439

I am not sure if it's issue on Raze or voxel pack side as I was able to load it using Raze 1.1.2
