### ISSUE TITLE
raze: voxel are not

### ISSUE THREAD

**Issue by Unikat2000** [fgsfds/Shadow-Warrior-Voxel-Pack#3]
Hi,
after quit a while I played Shadow Warrior on RAZE again and noticed that the voxels from this pack are not loaded / displayed anymore. After some investigation on my side  (clean RAZE 1.4.1 (also tried 1.3.1 and 1.2.1) install & fresh master branch copy, I really don't know what's wrong. (The voxel option in menu is ON and the build-in voxels are shown)

The Duke3D voxel pack works fine with RAZE and SW pack works fine on voidsw...    so I don't know where the culprit is....

**Comment by Dzierzan** [comment]
Hi,
How do you load them? What does raze.log say?

**Comment by Unikat2000** [comment]
Hi,

I tried both ways....    dragging the zip on the raze executable and via raze-xxxx.ini

[raze.log](https://github.com/fgsfds/Shadow-Warrior-Voxel-Pack/files/8504620/raze.log)

**Comment by Dzierzan** [comment]
Looks like it is loaded. What about addons for Shadow Warrior? Do they work? (HD sounds, skyboxes, whatever it can be)

**Comment by Unikat2000** [comment]
The SW upscale pack work.... regrading the your HDSounds I'm not so sure..... (maybe my ears are bad but I don't hear any difference...)

The sound configuration options are a little bit different now...

**Comment by Dzierzan** [comment]
When it comes to sounds: Launch Raze and go to Sound Options -> Advanced Options -> Turn on "Ignore file type  for sound lookup". Otherwise it won't work in Raze. You'll hear the difference.

Regarding voxels. I dunno how to help you. In my case, both dragging and dropping and using ini works fine. I wouldn't be suprised if there's a small typo or mistake somewhere. Keep looking. I recommend asking Raze guys as well.

**Comment by Unikat2000** [comment]
Yes, "Ignore file type for sound lookup" are on.....

I made a posting on the raze forum....

**Comment by Unikat2000** [comment]
this issue can be closed...  I figured it out:  You cannot use the ZIP from the master branch directly. It needs to be extracted and repacked, so that the def files are not in a subfolder.

I remember this being a issue for eduke32 and not raze, but it seems that something was changed....
